# Logs
logs/
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

# Dependency directories
node_modules/

# Build output
dist/
dist-ssr/

# Tauri build artifacts
/src-tauri/target/

# SQLite database and key files
journal.db
journal.key
*.db
*.key
.env
.env.local

# Editor directories and files
.vscode/
!.vscode/extensions.json
.idea/
.DS_Store
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?

# Configuration scripts
update-manifest.js
deploy-update.sh

# Miscellaneous
*.local
.cursor
tasks